# Generated by Django 2.2.24 on 2021-10-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cLogo',
        ),
    ]
